# Generated by Django 6.0.5 on 2026-06-23 08:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_remove_advertisement_video_url_advertisement_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
