# Generated by Django 6.0.5 on 2026-06-11 08:48

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('single_room', 'Single Room'), ('two_rooms', '2 Rooms'), ('flat', 'Flat'), ('apartment', 'Apartment'), ('house', 'House'), ('hostel', 'Hostel'), ('office', 'Office Space'), ('shutter', 'Shutter')], max_length=30)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=200)),
                ('ward_number', models.PositiveIntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('monthly_rent', models.PositiveIntegerField()),
                ('security_deposit', models.PositiveIntegerField()),
                ('available_date', models.DateField()),
                ('rules', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_parking', models.BooleanField(default=False)),
                ('bike_parking', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('drinking_water', models.BooleanField(default=False)),
                ('water_supply_24_7', models.BooleanField(default=False)),
                ('attached_bathroom', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('cctv', models.BooleanField(default=False)),
                ('security_guard', models.BooleanField(default=False)),
                ('pet_allowed', models.BooleanField(default=False)),
                ('laundry_facility', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
                ('generator', models.BooleanField(default=False)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
