# Generated by Django 6.0.5 on 2026-06-15 09:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citizenship_back_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='citizenship_back'),
        ),
        migrations.AddField(
            model_name='user',
            name='citizenship_front_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='citizenship_front'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_with_citizenship',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo_with_citizenship'),
        ),
    ]
