# Generated by Django 6.0.5 on 2026-06-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_verification_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('TENANT', 'Tenant'), ('LANDLORD', 'Landlord')], default=None, max_length=20, null=True),
        ),
    ]
